disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "gvdtech.net"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
description = "Linux and tech"
author = { headline = "A personal journey in Linux and tech", name = "Linux and Tech" }

#[params.author]
#image = "empty.png"
