[[main]]
none = "none"

[[main]]
name = "Home"
pageRef = "/"
identifier = "FKEszI1rPZ"
weight = 7

[[main]]
name = "Articles"
pageRef = "/posts"
identifier = "yr6CO5lK5F"
weight = 6

[[main]]
name = "Browse Categories"
pageRef = "/categories"
parent = "Categories"
weight = 6

[[main]]
name = "Browse Tags"
pageRef = "/tags"
parent = "Categories"
weight = 6

[[footer]]
none = "none"
